name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            { name: PandoProto, platform: linux/amd64, os: ubuntu-latest },
            { name: PandoProto, platform: windows/amd64, os: windows-latest },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false

      # Upload build assets
      - uses: actions/upload-artifact@v2
        with:
          name: Wails Build ${{runner.os}} ${{inputs.build-name}}
          path: |
            */bin/
            *\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */bin/*
